name: basic_crud_flutter
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.27.0
  cloud_firestore: ^4.17.3
  random_string: ^2.3.1
  fluttertoast: ^8.2.5
  http: ^1.2.1
  lottie: ^3.1.0
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  flutter_slidable: ^3.1.0
  google_fonts: ^6.2.1
  rive: ^0.13.2
  animated_text_kit: ^4.2.2
  animations: ^2.0.11
  image_picker: ^1.1.0
  firebase_storage: ^11.7.4
  introduction_screen: ^3.1.14
  get: ^4.6.6
  cached_network_image: ^3.3.1
  provider: ^6.1.2
  firebase_auth: ^4.19.5
  modal_progress_hud_nsn: ^0.5.1
  firebase_database: ^10.5.6
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/Images/
    - assets/Animations/
    - assets/Images/Mountain_images/
    - assets/Icons/
    # Assuming your images are in a folder named "images" in the root of your project
